### ISSUE TITLE
FastQC: Error: Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication

### ISSUE THREAD

**Issue by antonkulaga** [BioContainers/containers#154]
When I try to run 0.11.5--pl5.22.0_2 fastqc containers I get:
```
Error: Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication
```

**Comment by bgruening** [comment]
@antonkulaga how do you run this? This seems to work for me.
```
 docker run -it quay.io/biocontainers/fastqc:0.11.5--pl5.22.0_2 fastqc --help
```

**Comment by liyawang** [comment]
I ran into the same error. It seems that you can display the help message but it won't work with a real data.

**Comment by osallou** [comment]
how do you get error?
Launching a fake run (I have no test data), looks ok:

    root:~/minio# docker run   --rm quay.io/biocontainers/fastqc:0.11.5--pl5.22.0_2 fastqc some_file
    Failed to process some_file
    uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:89)
        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:106)
        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:129)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:102)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)

there is an error as input is not an expected sequence data, but we can see that application is loaded

**Comment by Sarathm03** [comment]
Downloaded fastqc
Unzipped it
Did chmod 755 fastqc
copied it to the home/bin
still getting this error "Error: Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication"
Can someone help

**Comment by osallou** [comment]
sorry but do you mean by download/unzip/... ? what is container relationship here ?
