### ISSUE TITLE
Picard Container fails on command "CollectInsertSizeMetrics"

### ISSUE THREAD

**Issue by josmos** [BioContainers/containers#200]
The run fails when its trying to execute an RScript. It seems there are some dependencies missing.
The same error occurs with picard images from quay.io

```
[Fri Jan 12 07:25:14 GMT 2018] picard.analysis.CollectInsertSizeMetrics HISTOGRAM_FILE=insert_size_histogram.pdf MINIMUM_PCT=0.05 INPUT=5C_view_sorted.bam OUTPUT=5C_metrics.txt    DEVIATIONS=10.0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_DUPLICATES=false ASSUME_SORTED=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
	[Fri Jan 12 07:25:14 GMT 2018] Executing as ?@4d163d247607 on Linux 3.16.0-5-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 2.9.2-SNAPSHOT
	INFO	2018-01-12 07:25:19	SinglePassSamProgram	Processed     1,000,000 records.  Elapsed time: 00:00:03s.  Time for last 1,000,000:    3s.  Last read position: NODE_8_length_145639_cov_114.951107:97,706
	INFO	2018-01-12 07:25:22	SinglePassSamProgram	Processed     2,000,000 records.  Elapsed time: 00:00:07s.  Time for last 1,000,000:    3s.  Last read position: NODE_21_length_74253_cov_116.506752:11,104
	INFO	2018-01-12 07:25:26	SinglePassSamProgram	Processed     3,000,000 records.  Elapsed time: 00:00:11s.  Time for last 1,000,000:    3s.  Last read position: NODE_45_length_44268_cov_105.927193:21,010
	INFO	2018-01-12 07:25:30	SinglePassSamProgram	Processed     4,000,000 records.  Elapsed time: 00:00:15s.  Time for last 1,000,000:    3s.  Last read position: NODE_181_length_8579_cov_54.016424:275
	INFO	2018-01-12 07:25:33	SinglePassSamProgram	Processed     5,000,000 records.  Elapsed time: 00:00:18s.  Time for last 1,000,000:    3s.  Last read position: NODE_467_length_4116_cov_61.304851:2,744
	INFO	2018-01-12 07:25:37	SinglePassSamProgram	Processed     6,000,000 records.  Elapsed time: 00:00:22s.  Time for last 1,000,000:    3s.  Last read position: NODE_3918_length_753_cov_5112.779370:430
	INFO	2018-01-12 07:25:38	RExecutor	Executing R script via command: Rscript /tmp/?/script7422107761240775482.R /data/5C_metrics.txt /data/insert_size_histogram.pdf 5C_view_sorted.bam
	[Fri Jan 12 07:25:38 GMT 2018] picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 0.40 minutes.
	Runtime.totalMemory()=711983104
	To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
	Exception in thread "main" htsjdk.samtools.SAMException: Unexpected exception executing [Rscript /tmp/?/script7422107761240775482.R /data/5C_metrics.txt /data/insert_size_histogram.pdf 5C_view_sorted.bam]
		at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:111)
		at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:87)
		at picard.util.RExecutor.executeFromFile(RExecutor.java:78)
		at picard.util.RExecutor.executeFromClasspath(RExecutor.java:59)
		at picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:166)
		at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:157)
		at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
		at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
		at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
		at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
	Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
		at java.lang.Runtime.exec(Runtime.java:620)
		at java.lang.Runtime.exec(Runtime.java:485)
		at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:102)
		... 9 more
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.lang.UNIXProcess.forkAndExec(Native Method)
		at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
		at java.lang.ProcessImpl.start(ProcessImpl.java:134)
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
		... 12 more`
```

**Comment by bgruening** [comment]
@josmos can you let us know how you start the container?

**Comment by josmos** [comment]
I was starting the container via the python-docker api. Starting the
container from the command line gives me the same error:

docker run -v /<pathtoinput>:/data/
quay.io/biocontainers/picard:2.9.2--py35_1 picard CollectInsertSizeMetrics
H=hist2.pdf I= /data/sorted.bam O=picard_out

INFO 2018-01-12 08:58:01 RExecutor Executing R script via command: Rscript
/tmp/root/script6258325217651305916.R /picard_out /hist2.pdf
5C_view_sorted.bam
[Fri Jan 12 08:58:01 GMT 2018] picard.analysis.CollectInsertSizeMetrics
done. Elapsed time: 0.40 minutes.
Runtime.totalMemory()=711983104
To get help, see
http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Unexpected
exception executing [Rscript /tmp/root/script6258325217651305916.R
/picard_out /hist2.pdf 5C_view_sorted.bam]
at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:111)
at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:87)
at picard.util.RExecutor.executeFromFile(RExecutor.java:78)
at picard.util.RExecutor.executeFromClasspath(RExecutor.java:59)
at
picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:166)
at
picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:157)
at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
at
picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No
such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at java.lang.Runtime.exec(Runtime.java:620)
at java.lang.Runtime.exec(Runtime.java:485)
at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:102)
... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 12 more


2018-01-12 9:21 GMT+01:00 Björn Grüning <notifications@github.com>:

**Comment by bgruening** [comment]
@josmos please see this discussion here: https://github.com/bioconda/bioconda-recipes/issues/3859

**Comment by alanhoyle** [comment]
This was recently fixed in the broadinstitute/picard:latest Docker image after a recent pull request.  https://github.com/broadinstitute/picard/pull/1198

That added r-base to the image and increased the size of the image by ~ 20%
