### ISSUE TITLE
Error running biocontainers/fastqc

### ISSUE THREAD

**Issue by kaylahardwick** [BioContainers/containers#220]
Hello,

I am trying to run the fastqc container, and getting the following error:

Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:332)

The command I used was:

sudo docker run -it biocontainers/fastqc

I get the same error if I try to run the program without the -it flags.

Thanks for your help!

**Comment by kaylahardwick** [comment]
I just realized this error message is due to running fastqc without input files specified. The following command worked perfectly:

sudo docker run -v $(pwd):/data biocontainers/fastqc fastqc R1_file.fastq.gz R2_file.fastq.gz

Thanks!
