### ISSUE TITLE
Picard container issue

### ISSUE THREAD

**Issue by tushardave26** [BioContainers/containers#233]
Hello,

Recently, I tried to use the Picard container image from `Quay`. I tried to run the following command line with the container and it failed on me because of R is not available in the container image.

`sudo docker run --rm -e JAVA_OPTS='-Xmx24G' -v /home/tushardave26:/data quay.io/biocontainers/picard:2.18.4--py36_0 picard CollectInsertSizeMetrics HISTOGRAM_FILE=/data/picard.hist.file.pdf INPUT=/data/pmd_out.mrkdup.bam OUTPUT=/data/picard.insertsize.out STOP_AFTER=1000000` 

Following is the error message that I received:
`
Exception in thread "main" htsjdk.samtools.SAMException: Unexpected exception executing [Rscript /tmp/root/script8740309689205235475.R /data/picard.insertsize.out /data/picard.hist.file.pdf pmd_out.mrkdup.bam]
	at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:111)
	at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:87)
	at picard.util.RExecutor.executeFromFile(RExecutor.java:78)
	at picard.util.RExecutor.executeFromClasspath(RExecutor.java:59)
	at picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:168)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:164)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:102)
	... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 12 more
`
Is it possible to get the required packages to be installed in the container image?

Thanks for the help.

Best,
Tushar

**Comment by bgruening** [comment]
@tushardave26 please chime in here: https://github.com/bioconda/bioconda-recipes/issues/3859
