### ISSUE TITLE
fastqc dont works

### ISSUE THREAD

**Issue by arturomarin** [BioContainers/containers#262]
We are trying to use the fastqc docker installed on a server. Using
a computer with windows and PuTYY we have no problem, but from Linux
and Mac OS we can not use fastqc.

#From the local computer we do:
`$ ssh -X <user>@<Server IP> `

#In the server:
```
$ export DISPLAY=<IP of the local computer>:0.0
$ xhost +; docker run -v /home/amarin/datos_amarin/:/data/ -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -it --rm biocontainers/fastqc fastqc 

```
#And the server gives us the following error:
```
xhost:  unable to open display "10.11.0.10:0.0"
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using '10.11.0.10:0.0' as the value of the DISPLAY variable.
    at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
    at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
    at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
    at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at java.awt.Toolkit$2.run(Toolkit.java:860)
    at java.awt.Toolkit$2.run(Toolkit.java:855)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
    at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
    at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:322) 

```
#But the xeyes command works

Thanks in advance

**Comment by osallou** [comment]
I tested on my local computer (ubuntu) and it works.

    sudo docker run  -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -it --rm biocontainers/fastqc fastqc

xeyes works on your <IP of the local computer> ?

Maybe a xauthority/x11 problem on your server.

**Comment by arturomarin** [comment]
Thanks, but I do not think that is because we can connect to the server without any problem. xauthority seems fine.  The problem is something related to the redirection of the X, which using PuTTY does work but not on Mac / Linux. 

yes, xeyes works,... but not the export of X's when using fastqc.

**Comment by ypriverol** [comment]
@arturomarin have you solve this issue.

**Comment by arturomarin** [comment]
I apologize for the delay in answering. We had problems with the server hardware and had to stop installing programs on the server. You can close the issue, and if I try again to install the program and I have problems I will post an issue.

**Comment by MattBrauer** [comment]
This is an issue with XQuartz permissions. see here: https://medium.com/@mreichelt/how-to-show-x11-windows-within-docker-on-mac-50759f4b65cb
