### ISSUE TITLE
fastQC fails with Java errors

### ISSUE THREAD

**Issue by JWDebler** [BioContainers/containers#389]
I tried running the latest fastQC container (`biocontainers/fastqc        v0.11.9_cv6`) , but it keeps failing at the very end with this:

```
Approx 95% complete for 30_E_L003_R1.fq.gz
Analysis complete for 30_E_L003_R1.fq.gz
Failed to process file 30_E_L003_R1.fq.gz
java.lang.NullPointerException
     at sun.awt.FontConfiguration.getVersion(java.desktop@9-internal/FontConfiguration.java:1264)
     at sun.awt.FontConfiguration.readFontConfigFile(java.desktop@9-internal/FontConfiguration.java:219)
     at sun.awt.FontConfiguration.init(java.desktop@9-internal/FontConfiguration.java:107)
     at sun.awt.X11FontManager.createFontConfiguration(java.desktop@9-internal/X11FontManager.java:773)
     at sun.font.SunFontManager$2.run(java.desktop@9-internal/SunFontManager.java:433) 
    at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method) 
     at sun.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-internal/NativeConstructorAccessorImpl.java:62)
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-internal/DelegatingConstructorAccessorImpl.java:45) 
     at java.lang.reflect.Constructor.newInstance(java.base@9-internal/Constructor.java:453) 
     at java.lang.Class.newInstance(java.base@9-internal/Class.java:550) 
     at sun.font.FontManagerFactory$1.run(java.desktop@9-internal/FontManagerFactory.java:83) 
     at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method) 
     at sun.font.FontManagerFactory.getInstance(java.desktop@9-internal/FontManagerFactory.java:74)
     at sun.font.SunFontManager.getInstance(java.desktop@9-internal/SunFontManager.java:252) 
     at sun.font.FontDesignMetrics.getMetrics(java.desktop@9-internal/FontDesignMetrics.java:264) 
     at sun.java2d.SunGraphics2D.getFontMetrics(java.desktop@9-internal/SunGraphics2D.java:856) 
     at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
     at javax.swing.JComponent.print(java.desktop@9-internal/JComponent.java:1203)
     at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68) 
     at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199) 
     at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131) 
     at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:185)  
     at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:123) 
     at java.lang.Thread.run(java.base@9-internal/Thread.java:804)   
```

**Comment by osallou** [comment]
It tries some x11 font related access, but there us no x11 in containers.
You may try to run java in headless mide.

**Comment by JWDebler** [comment]
I am just running fastQC as I did in the past with a local installation. Not sure what to do differently.

**Comment by osallou** [comment]
In a container, you are just like on a remote server ie with no graphical support
In this mode, apps using x11 display lib fail, in java using headless mode usually solve the issue (as long as no real gui is expected of course)

**Comment by JWDebler** [comment]
I get the idea, but I how do I run fastqc via docker in that mode? In the
past I just had to use "fastqc *.fastq.gz".

Am Fr., 9. Okt. 2020 um 12:54 Uhr schrieb Olivier Sallou <
notifications@github.com>:

**Comment by osallou** [comment]
seems headless mode is set by fastqc, but does not seem to work even with option....

**Comment by osallou** [comment]
even mounting local X11 fails for me

**Comment by osallou** [comment]
seems to fail with java 9, with  java 8 seems to work
I have updated recipe and should work with v0.11.9_cv7 (build in progress)
